name= "ramen-api"
workers_dev = false

routes = ["ramen-api.dev/*"]

compatibility_date = "2022-03-23"

main = "./dist/index.js"

[build]
command = "yarn run build"

[site]
bucket = "./content"

[vars]
ENV_BASE_URL = "https://ramen-api.dev/"